### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by d-dorazio** [lvillani/releng#3]
```
⋊> ~/D/a/r/python(royal-jelly)|master⚡*?$ releng run -- foo
+ foo
panic: interface conversion: error is *exec.Error, not *exec.ExitError

goroutine 1 [running]:
panic(0x2e7c40, 0xc420076700)
	/usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:500 +0x1a1
main.call(0xc420076170, 0x1, 0x1, 0xbda11)
	/Users/daniele/Development/go/src/github.com/lvillani/releng/releng.go:452 +0x2d4
main.run(0xc4200e4500)
	/Users/daniele/Development/go/src/github.com/lvillani/releng/releng.go:371 +0x5a
github.com/codegangsta/cli.HandleAction(0x2ca200, 0x3604a0, 0xc4200e4500, 0xc420074300, 0x0)
	/Users/daniele/Development/go/src/github.com/codegangsta/cli/app.go:473 +0x61
github.com/codegangsta/cli.Command.Run(0x336109, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x346dfc, 0x40, 0x0, ...)
	/Users/daniele/Development/go/src/github.com/codegangsta/cli/command.go:191 +0xcc7
github.com/codegangsta/cli.(*App).Run(0xc420065520, 0xc420076140, 0x4, 0x4, 0x0, 0x0)
	/Users/daniele/Development/go/src/github.com/codegangsta/cli/app.go:241 +0x6a3
main.main()
	/Users/daniele/Development/go/src/github.com/lvillani/releng/releng.go:203 +0x429
```

**Comment by lvillani** [comment]
The error happens while trying to execute `foo` which isn't in the `$PATH`
